### ISSUE TITLE
Broken encumbrance visual effect and incorrect weight values when on a server 

### ISSUE THREAD

**Issue by Pingu-Pox** [WolfieWaffle/Inventory-Weight#1]
**Describe the bug**
All items/blocks on the server (with a matching config as the client) are set to the default weight of 1.0, regardless of what the config says. If the player first opens a single player world, where the weights are correctly set from the config (for instance, ores being 8.0), and then connects to the server, the weights are then applied correctly.

Also, when the server weight is incorrectly set, and the player reaches a weight of 19, the encumbered visual effect kicks in BUT it seems broken and is constantly zooming in and out like the effect is being canceled.

**To Reproduce**
1. Connect to server that has matching Inventory Weights config files.
2. Observe that weights are incorrectly set
3. Grab a stack of items, and observe broken encumbrance visual effect
4. Optionally make a single player world, then go back to the server to see that the issue is fixed... but it's only for the current session. If you close the game client and relaunch it, you have to open the single player world again before the server acts as expected.

**Expected behavior**
Weight values should be properly set on the server, and the visual encumbrance effect should not be bugging out.

**Screenshots**
Here's a video demonstrating the issue: https://www.youtube.com/watch?v=GacaQYrVxBY

**Environment:**
 - Forge: 40.1.73
 - Inventory Weight: 1.1

**Additional context**
We've tried this in a heavily modded server and a completely stripped down server that just had the Inventory Weight mod, same behavior.

**Comment by WolfieWaffle** [comment]
huh weird, ill try to look into it when I start seriously working on this mod again

**Comment by WolfieWaffle** [comment]
I have fixed this in the latest version, gonna build soon. sorry for late response.

**Comment by Pingu-Pox** [comment]
This is confirmed fixed, thank you!!!!
